function showHelp() {
	#
	# Display commandline help on STDOUT.
	#
	cat <<EOH
======================================================================================================================
Script generate curl command, to upload all vcf files of parents in the parents sample file.
Usage:
	$(basename "${0}") OPTIONS
Options:
	-h	Show this help.
	-d	The directory containing the vcf files.
	-m	txt file from Moon JSON output file, containing all samples with Moon number.
	-t	token from moon. Connecting you to your moon account.
	-e	Email adres used by moon.
===============================================================================================================
EOH
	trap - EXIT
	exit 0
}

#
##
### Main.
##
#

#
# Get commandline arguments.
#
declare project=''
while getopts "d:p:m:t:e:h" opt
do
	case "${opt}" in
		h)
			showHelp
			;;
		d)
			vcfFileDir="${OPTARG}"
			;;
		m)
			MoonTxt="${OPTARG}"
			;;
		t)
			token="${OPTARG}"
			;;
		e)
			email="${OPTARG}"
			;;
	esac
done

#
# Check commandline options.
#

if [[ -z "${vcfFileDir:-}" ]]
then
	echo 'Must specify a directory with vcf files with -d.'
	exit 0
fi

if [[ -z "${MoonTxt}:-" ]]
then
	echo 'Must specify an .txt file generated by readJsonFile.py. Samplesheet with patient-parent information.'
	exit 0
fi
if [[ -z "${token:-}" ]]
then
	echo 'Must specify your user token from moon with -t.'
	exit 0
fi
if [[ -z "${email:-}" ]]
then
	echo 'Must specify your email adres used by moon with -e.'
	exit 0
fi


for i in $(awk '{if (NR>1){{print $0}}}' "${MoonTxt}")
do
#	echo "${i}"	
	VCF=$(echo "${i}" | cut -d "," -f 1)
	GENDER=$(echo "${i}" | cut -d "," -f 2)
	PROJECT=$(echo "${i}" | cut -d "," -f 3)
	AGE=$(echo "${i}" | cut -d "," -f 4)
	HPO_TERMS=$(echo "${i}" | cut -d "," -f 5)
	MOTHERHEALTH=$(echo "${i}" | cut -d "," -f 7)
	MOTHERID=$(echo "${i}" | cut -d "," -f 10)
	FATHERHEALTH=$(echo "${i}" | cut -d "," -f 9)
	FATHERID=$(echo "${i}" | cut -d "," -f 11)
	FAMILY_MEMBERS=$(echo "${MOTHERID}:${MOTHERHEALTH}:mother;${FATHERID}:${FATHERHEALTH}:father")
#	echo "MOTHERID:MOTHERHEALTH: ${MOTHERID}:${MOTHERHEALTH}"
#	echo "FATHERID:FATHERHEALTH: ${FATHERID}:${FATHERHEALTH}"
#	echo "${FAMILY_MEMBERS}"

	echo "curl -F "user_token="${token}""\
     -F "user_email="${email}""\
     -F "snp_vcf_file=@/"${vcfFileDir}/${VCF}".vcf.gz"\
     -F "gender="${GENDER}""\
     -F "project_id="${PROJECT}""\
     -F "age="${AGE}""\
     -F "hpo_terms="${HPO_TERMS}""\
     -F "family_members="${FAMILY_MEMBERS}""	
     https://moon.diploid.com/samples.json"

	curl -F "user_token="${token}""\
     -F "user_email="${email}""\
     -F "snp_vcf_file=@/"${vcfFileDir}/${VCF}".vcf.gz"\
     -F "gender="${GENDER}""\
     -F "project_id="${PROJECT}""\
     -F "age="${AGE}""\
     -F "hpo_terms="${HPO_TERMS}""\
     -F "family_members="${FAMILY_MEMBERS}""	
     https://moon.diploid.com/samples.json

done
